parameters:
  - name: src
    displayName: Source Branch
    type: string
    default: master
  - name: dest
    displayName: Destination Branch
    type: string
    default: staging
  - name: package
    displayName: Use --package <package> or --workspace to release all packages
    type: string
    default: --workspace
  - name: level
    displayName: Level (major|minor|patch|rc|alpha|beta|release|<version>)
    type: string
    default: rc
  - name: args
    displayName: Cargo Release Extra Args
    type: string
    default: --no-confirm --skip-push --skip-publish 
  - name: name
    displayName: Author Name
    type: string
    default: sa-sawp
  - name: email
    displayName: Author Email
    type: string
    default: sa-sawp@cyber.gc.ca

trigger: none
pr: none

resources:
- repo: self

jobs:
- job: release_sawp
  displayName: Release SAWP
  pool: sawp-builders
  steps:
    # SAWP Steps
    # ==============
    - checkout: self
      clean: true
      path: sawp
      persistCredentials: true
    
    # Configure author to commit release with
    - script: git config user.name ${{ parameters.name }}
    - script: git config user.email ${{ parameters.email }}

    # The src branch is the code you want to release -- e.g. master
    # The dest branch is where you want the code to go -- e.g. staging
    - script: git remote update origin
      displayName: update
    - script: git checkout ${{ parameters.dest }} && git pull --ff-only origin ${{ parameters.dest }} && git merge --ff-only origin/${{ parameters.src }} || git checkout -b ${{ parameters.dest }} origin/${{ parameters.src }}
      displayName: merge

    # Check all contributors are in .contributors list
    - script: chmod +x ./.contributors.sh && ./.contributors.sh -r ${{ parameters.dest }}
      displayName: contributors

    # QA Checks
    # ==============
    - template: qa-steps.yml

    # Release
    # ==============

    # Check if cargo release is installed
    - script: cargo release --help > /dev/null || cargo install cargo-release
      displayName: install cargo-release

    # Commit and tag the release
    - script: cargo release ${{ parameters.package }} ${{ parameters.args }} -- ${{ parameters.level }}
      displayName: cargo release

    # Don't push with cargo release because it will fail
    - script: git push --follow-tags origin ${{ parameters.dest }}

    # Release Artifacts
    # ==============
    - template: package-steps.yml

    # Get the package version
    - script: echo "##vso[task.setvariable variable=version]$((test -f Cargo.lock || cargo generate-lockfile) && cargo pkgid | cut -d# -f 2)"
      displayName: package version

    # Push RPM to repository
    - script: azure/deploy-rpm.sh
      env:
        SRC_DIR: target/rpmbuild/RPMS/x86_64
        SRC_PATTERN: sawp-$(version)*.rpm
        RPM_HOST: $(rpm_host)
        RPM_USER: $(rpm_user)
        RPM_DIR: $(rpm_dir)
        RPM_CHOWN: root:root
        RPM_CHMOD: 644
