[package]
name = "sawp"
version = "0.1.1-rc.3"
authors = ["Canadian Centre for Cyber Security <sa-sawp@cyber.gc.ca>"]
description = "Security Aware Wire Protocol parsing library"
readme = "README.md"
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/CybercentreCanada/sawp"
homepage = "https://github.com/CybercentreCanada/sawp"
keywords = ["parser", "streaming", "protocols", "network", "api"]
categories = ["parsing", "network-programming"]
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/**/*.rs",
]

[workspace]
members = [
    "sawp-modbus",
    "sawp-file",
    "sawp-json",
    "sawp-diameter",
]

[features]
# Makes error messages more descriptive and verbose at the cost of allocating
# more strings
verbose = []

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
bench = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
nom = "5.1.2"

[[bench]]
name = "modbus"
path = "benches/modbus.rs"
harness = false

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
"libsawp.so" = { path = "/usr/local/lib/libsawp.so" }
"libsawp_diameter.so" = { path = "/usr/local/lib/libsawp_diameter.so" }
"libsawp_modbus.so" = { path = "/usr/local/lib/libsawp_modbus.so" }
"libsawp_json.so" = { path = "/usr/local/lib/libsawp_json.so" }

[package.metadata.release]
pre-release-replacements = [
  {file="README.md", search="sawp = .*", replace="sawp = \"{{version}}\""},
]
