[package]
name = "sawp"
version = "0.1.0"
authors = ["cccs-rtmorti", "cccs-sadugas"]
description = "Security Aware Wire Protocol parsing library"
readme = "README.md"
edition = "2018"
license-file = "LICENSE"

[workspace]
members = [
    "sawp-modbus",
    "sawp-file",
    "sawp-json",
]

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[dev-dependencies]
criterion = "0.3"

[dependencies]
nom = "5.1.2"

[[bench]]
name = "modbus"
harness = false

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
"libsawp.so" = { path = "/usr/local/lib/libsawp.so" }
"libsawp_modbus.so" = { path = "/usr/local/lib/libsawp_modbus.so" }
"libsawp_json.so" = { path = "/usr/local/lib/libsawp_json.so" }
