# These settings are shared across all workspace packages
# Use Cargo.toml to customize settings for a particular package.
enable-all-features=true

# Handled in CI pipeline.
publish=false
push=false

# Release all workspace packages in a single commit.
consolidate-commits=true

# There is a missing feature in cargo-release preventing replacements
# like {{version}} from working in "consolidate-commits" mode.
pre-release-commit-message="sawp: release package(s)"

# Tags have an rpm-like versioning scheme.
# E.g. sawp-0.1.0-rc.1
tag-prefix="{{crate_name}}"
tag-name="{{prefix}}-{{version}}"

# This will update the version of sawp in workspace packages
# for all releases (major|minor|patch|rc|...).
dependent-version="upgrade"

# Updates the README.md and CHANGELOG.md so we don't have to
pre-release-replacements = [
  {file="README.md", search="sawp = \"[a-z0-9\\.-]+\"", replace="sawp = \"{{version}}\"", exactly=1},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="compare/[a-z0-9\\.-]+\\.\\.\\.HEAD", replace="releases/tag/{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/CybercentreCanada/sawp/compare/{{tag_name}}...HEAD", exactly=1},
]
