[package]
name = "sawp-modbus"
version = "0.1.0"
authors = ["cccs-sadugas"]
readme = "../README.md"
edition = "2018"
license-file = "../LICENSE"

[dependencies]
sawp = { path = ".." }
nom = "5.1.2"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
rstest = "0.6.4"
