[package]
name = "sawp-json"
version = "0.1.0"
authors = ["sharksforarms"]
readme = "../README.md"
edition = "2018"
license-file = "../LICENSE"

[dependencies]
sawp = { path = ".." }
serde = "1.0"
serde_json = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3"
rstest = "0.6"

[[bench]]
name = "json"
harness = false
